all:    bin/mhs.exe bin/mhseval.exe

# Compile mhs from distribution, with C compiler
bin/mhs.exe:	src/runtime/eval.c src/runtime/config*.h #generated/mhs.c
	@-mkdir bin
	cl /O2 src/runtime/eval.c generated/mhs.c /Febin/mhs.exe

# Compile combinator evaluator
bin/mhseval.exe:	src/runtime/eval.c src/runtime/config*.h src/runtime/comb.c
	@-mkdir bin
	cl /O2 src/runtime/eval.c src/runtime/comb.c /Febin/mhseval.exe
