-- Copyright 2023 Lennart Augustsson
-- See LICENSE file for full license.
{-# OPTIONS_GHC -Wno-unused-imports #-}
module MicroHs.Translate(
  translate,
  TranslateMap,
  translateMap,
  translateWithMap,
  translateAndRun
  ) where
import qualified Prelude(); import MHSPrelude
import Data.ByteString.Internal(ByteString)
import Data.Maybe
import Data.String
import Unsafe.Coerce

import PrimTable
import MicroHs.Desugar(LDef, encodeInteger)
import MicroHs.Expr
import MicroHs.Exp
import MicroHs.ExpPrint(encodeString)
import MicroHs.Ident
import qualified MicroHs.IdentMap as M
import Text.PrettyPrint.HughesPJLiteClass(prettyShow)

translateAndRun :: ([LDef], Exp) -> IO ()
translateAndRun defs = do
  let prog = unsafeCoerce (translate defs)
  prog

type TranslateMap = M.Map AnyType

trLookup :: TranslateMap -> Ident -> AnyType
trLookup mp n = fromMaybe (errorMessage (getSLoc n) $ "translate: not found " ++ showIdent n) $ M.lookup n mp

translateMap :: [LDef] -> TranslateMap
translateMap ds =
  let mp = M.fromList [(n, translateExp mp d) | (n, d) <- ds ]
  in  mp

translateExp :: TranslateMap -> Exp -> AnyType
translateExp mp e = trans (trLookup mp) e

translateWithMap :: TranslateMap -> ([LDef], Exp) -> AnyType
translateWithMap mp (ds, e) =
  let mp' = foldr (\ (i, d) -> M.insert i (translateExp mp' d)) mp ds
  in  translateExp mp' e

translate :: ([LDef], Exp) -> AnyType
translate (ds, e) = translateExp (translateMap ds) e

trans :: (Ident -> AnyType) -> Exp -> AnyType
trans r ae =
  case ae of
    Var n -> r n
    App f a -> unsafeCoerce (trans r f) (trans r a)
    Lit (LInt i) -> unsafeCoerce i
    Lit (LInt64 i) -> unsafeCoerce i
    Lit (LDouble i) -> unsafeCoerce i
    Lit (LFloat i) -> unsafeCoerce i
    Lit (LStr s) -> trans r (encodeString s)
    Lit (LBStr s) -> unsafeCoerce s
    Lit (LPrim p) -> lookupPrim p
    Lit (LInteger i) -> trans r (encodeInteger i)
    Lit f@(LForImp _ _ _ _) -> trans r (App (Lit (LPrim "dynsym")) (Lit (LStr (drop 1 $ showLit f))))
    _ -> error $ "trans: impossible: " ++ prettyShow ae

lookupPrim :: String -> AnyType
lookupPrim s = fromMaybe (error $ "trans: no primop " ++ show s) $
               M.lookup (mkIdent s) primIdentTable

primIdentTable :: M.Map AnyType
primIdentTable = M.fromList [(mkIdent s, p) | (s, p) <- primTable]

primTable :: [(String, AnyType)]
primTable = [
  ("B", _primitive "B"),
  ("O", _primitive "O"),
  ("K", _primitive "K"),
  ("C'", _primitive "C'"),
  ("C", _primitive "C"),
  ("A", _primitive "A"),
  ("S'", _primitive "S'"),
  ("P", _primitive "P"),
  ("I", _primitive "I"),
  ("S", _primitive "S"),
  ("U", _primitive "U"),
  ("Y", _primitive "Y"),
  ("B'", _primitive "B'"),
  ("Z", _primitive "Z"),
  ("J", _primitive "J"),
  ("R", _primitive "R"),
  ("K2", _primitive "K2"),
  ("K3", _primitive "K3"),
  ("K4", _primitive "K4"),
  ("C'B", _primitive "C'B"),
  ("L", _primitive "L"),
  ("KK", _primitive "KK"),
  ("KA", _primitive "KA"),
  ("T3", _primitive "T3"),
  ("T4", _primitive "T4"),
  ("T5", _primitive "T5"),
  ("T6", _primitive "T6"),
  ("T7", _primitive "T7"),
  ("T8", _primitive "T8"),
  ("T9", _primitive "T9"),
  ("T10", _primitive "T10"),
  ("T11", _primitive "T11"),
  ("T12", _primitive "T12"),
  ("T13", _primitive "T13"),
  ("T14", _primitive "T14"),
  ("T15", _primitive "T15"),
  ("T16", _primitive "T16"),
  ("TAG0", _primitive "TAG0"),
  ("TAG1", _primitive "TAG1"),
  ("TAG2", _primitive "TAG2"),
  ("TAG3", _primitive "TAG3"),
  ("TAG4", _primitive "TAG4"),
  ("TAG5", _primitive "TAG5"),
  ("TAG6", _primitive "TAG6"),
  ("TAG7", _primitive "TAG7"),
  ("TAG8", _primitive "TAG8"),
  ("TAG9", _primitive "TAG9"),
  ("TAG10", _primitive "TAG10"),
  ("TAG11", _primitive "TAG11"),
  ("TAG12", _primitive "TAG12"),
  ("TAG13", _primitive "TAG13"),
  ("TAG14", _primitive "TAG14"),
  ("TAG15", _primitive "TAG15"),
  ("TAG16", _primitive "TAG16"),
  ("TAG17", _primitive "TAG17"),
  ("TAG18", _primitive "TAG18"),
  ("TAG19", _primitive "TAG19"),
  ("TAG20", _primitive "TAG20"),
  ("TAG21", _primitive "TAG21"),
  ("TAG22", _primitive "TAG22"),
  ("TAG23", _primitive "TAG23"),
  ("TAG24", _primitive "TAG24"),
  ("TAG25", _primitive "TAG25"),
  ("TAG26", _primitive "TAG26"),
  ("TAG27", _primitive "TAG27"),
  ("TAG28", _primitive "TAG28"),
  ("TAG29", _primitive "TAG29"),
  ("TAG30", _primitive "TAG30"),
  ("TAG31", _primitive "TAG31"),
  ("TAG32", _primitive "TAG32"),
  ("+", _primitive "+"),
  ("-", _primitive "-"),
  ("*", _primitive "*"),
  ("quot", _primitive "quot"),
  ("rem", _primitive "rem"),
  ("neg", _primitive "neg"),
  ("u+", _primitive "u+"),
  ("u-", _primitive "u-"),
  ("u*", _primitive "u*"),
  ("uquot", _primitive "uquot"),
  ("urem", _primitive "urem"),
  ("uneg", _primitive "uneg"),
  ("and", _primitive "and"),
  ("or", _primitive "or"),
  ("xor", _primitive "xor"),
  ("inv", _primitive "inv"),
  ("shl", _primitive "shl"),
  ("shr", _primitive "shr"),
  ("ashr", _primitive "ashr"),
  ("subtract", _primitive "subtract"),
  ("usubtract", _primitive "usubtract"),
  ("popcount", _primitive "popcount"),
  ("clz", _primitive "clz"),
  ("ctz", _primitive "ctz"),
  ("==", _primitive "=="),
  ("/=", _primitive "/="),
  ("<", _primitive "<"),
  ("<=", _primitive "<="),
  (">", _primitive ">"),
  (">=", _primitive ">="),
  ("u<", _primitive "u<"),
  ("u<=", _primitive "u<="),
  ("u>", _primitive "u>"),
  ("u>=", _primitive "u>="),
  ("ord", _primitive "ord"),
  ("chr", _primitive "chr"),
  ("f+", _primitive "f+"),
  ("f-", _primitive "f-"),
  ("f*", _primitive "f*"),
  ("f/", _primitive "f/"),
  ("f==", _primitive "f=="),
  ("f/=", _primitive "f/="),
  ("f<", _primitive "f<"),
  ("f<=", _primitive "f<="),
  ("f>", _primitive "f>"),
  ("f>=", _primitive "f>="),
  ("fneg", _primitive "fneg"),
  ("itof", _primitive "itof"),
  ("utof", _primitive "utof"),
  ("ftoi", _primitive "ftoi"),
  ("Itof", _primitive "Itof"),
  ("ftod", _primitive "ftod"),
  ("dtof", _primitive "dtof"),
  ("d+", _primitive "d+"),
  ("d-", _primitive "d-"),
  ("d*", _primitive "d*"),
  ("d/", _primitive "d/"),
  ("d==", _primitive "d=="),
  ("d/=", _primitive "d/="),
  ("d<", _primitive "d<"),
  ("d<=", _primitive "d<="),
  ("d>", _primitive "d>"),
  ("d>=", _primitive "d>="),
  ("dneg", _primitive "dneg"),
  ("itod", _primitive "itod"),
  ("utod", _primitive "utod"),
  ("Itod", _primitive "Itod"),
  ("dtoi", _primitive "dtoi"),
  ("seq", _primitive "seq"),
  ("icmp", _primitive "icmp"),
  ("ucmp", _primitive "ucmp"),
  ("rnf", _primitive "rnf"),
  ("IO.>>=", _primitive "IO.>>="),
  ("IO.>>", _primitive "IO.>>"),
  ("IO.return", _primitive "IO.return"),
  ("IO.print", _primitive "IO.print"),
  ("IO.serialize", _primitive "IO.serialize"),
  ("IO.deserialize", _primitive "IO.deserialize"),
  ("IO.stdin", _primitive "IO.stdin"),
  ("IO.stdout", _primitive "IO.stdout"),
  ("IO.stderr", _primitive "IO.stderr"),
  ("IO.getArgRef", _primitive "IO.getArgRef"),
  ("IO.performIO", _primitive "IO.performIO"),
  ("IO.atomic", _primitive "IO.atomic"),
  ("IO.gc", _primitive "IO.gc"),
  ("IO.stats", _primitive "IO.stats"),
  ("raise", _primitive "raise"),
  ("catch", _primitive "catch"),
  ("dynsym", _primitive "dynsym"),
  ("bsnew", _primitive "bsnew"),
  ("bsappbyte", _primitive "bsappbyte"),
  ("bsappchar", _primitive "bsappchar"),
  ("bsfreeze", _primitive "bsfreeze"),
  ("packCString", _primitive "packCString"),
  ("packCStringLen", _primitive "packCStringLen"),
  ("toInt", _primitive "toInt"),
  ("toPtr", _primitive "toPtr"),
  ("toDbl", _primitive "toDbl"),
  ("toFlt", _primitive "toFlt"),
  ("fromDbl", _primitive "fromDbl"),
  ("fromFlt", _primitive "fromFlt"),
  ("toFunPtr", _primitive "toFunPtr"),
  ("A.alloc", _primitive "A.alloc"),
  ("A.copy", _primitive "A.copy"),
  ("A.size", _primitive "A.size"),
  ("A.read", _primitive "A.read"),
  ("A.write", _primitive "A.write"),
  ("A.trunc", _primitive "A.trunc"),
  ("A.==", _primitive "A.=="),
  ("bs++", _primitive "bs++"),
  ("bs++.", _primitive "bs++."),
  ("bs==", _primitive "bs=="),
  ("bs/=", _primitive "bs/="),
  ("bs<", _primitive "bs<"),
  ("bs<=", _primitive "bs<="),
  ("bs>", _primitive "bs>"),
  ("bs>=", _primitive "bs>="),
  ("bscmp", _primitive "bscmp"),
  ("bsunpack", _primitive "bsunpack"),
  ("bsreplicate", _primitive "bsreplicate"),
  ("bslength", _primitive "bslength"),
  ("bssubstr", _primitive "bssubstr"),
  ("bsindex", _primitive "bsindex"),
  ("bswrite", _primitive "bswrite"),
  ("bsread", _primitive "bsread"),
  ("fromUTF8", _primitive "fromUTF8"),
  ("headUTF8", _primitive "headUTF8"),
  ("tailUTF8", _primitive "tailUTF8"),
  ("fp+", _primitive "fp+"),
  ("fp2p", _primitive "fp2p"),
  ("fpnew", _primitive "fpnew"),
  ("fpfin", _primitive "fpfin"),
  ("fp2bs", _primitive "fp2bs"),
  ("bs2fp", _primitive "bs2fp"),
  ("bsgrab", _primitive "bsgrab"),
  ("bsgrablen", _primitive "bsgrablen"),
  ("IO.fork", _primitive "IO.fork"),
  ("IO.thid", _primitive "IO.thid"),
  ("IO.waitrdfd", _primitive "IO.waitrdfd"),
  ("IO.waitwrfd", _primitive "IO.waitwrfd"),
  ("thnum", _primitive "thnum"),
  ("IO.throwto", _primitive "IO.throwto"),
  ("IO.yield", _primitive "IO.yield"),
  ("IO.newmvar", _primitive "IO.newmvar"),
  ("IO.takemvar", _primitive "IO.takemvar"),
  ("IO.putmvar", _primitive "IO.putmvar"),
  ("IO.readmvar", _primitive "IO.readmvar"),
  ("IO.trytakemvar", _primitive "IO.trytakemvar"),
  ("IO.tryputmvar", _primitive "IO.tryputmvar"),
  ("IO.tryreadmvar", _primitive "IO.tryreadmvar"),
  ("IO.threaddelay", _primitive "IO.threaddelay"),
  ("IO.threadstatus", _primitive "IO.threadstatus"),
  ("isint", _primitive "isint"),
  ("SPnew", _primitive "SPnew"),
  ("SPderef", _primitive "SPderef"),
  ("SPfree", _primitive "SPfree"),
  ("I+", _primitive "I+"),
  ("I-", _primitive "I-"),
  ("I*", _primitive "I*"),
  ("Iquot", _primitive "Iquot"),
  ("Irem", _primitive "Irem"),
  ("Ineg", _primitive "Ineg"),
  ("Iu+", _primitive "Iu+"),
  ("Iu-", _primitive "Iu-"),
  ("Iu*", _primitive "Iu*"),
  ("Iuquot", _primitive "Iuquot"),
  ("Iurem", _primitive "Iurem"),
  ("Iuneg", _primitive "Iuneg"),
  ("Iand", _primitive "Iand"),
  ("Ior", _primitive "Ior"),
  ("Ixor", _primitive "Ixor"),
  ("Ishl", _primitive "Ishl"),
  ("Ishr", _primitive "Ishr"),
  ("Iashr", _primitive "Iashr"),
  ("Iinv", _primitive "Iinv"),
  ("Isubtract", _primitive "Isubtract"),
  ("Iusubtract", _primitive "Iusubtract"),
  ("Ipopcount", _primitive "Ipopcount"),
  ("Iclz", _primitive "Iclz"),
  ("Ictz", _primitive "Ictz"),
  ("I==", _primitive "I=="),
  ("I/=", _primitive "I/="),
  ("I<", _primitive "I<"),
  ("I<=", _primitive "I<="),
  ("I>", _primitive "I>"),
  ("I>=", _primitive "I>="),
  ("Iicmp", _primitive "Iicmp"),
  ("Iu<", _primitive "Iu<"),
  ("Iu<=", _primitive "Iu<="),
  ("Iu>", _primitive "Iu>"),
  ("Iu>=", _primitive "Iu>="),
  ("Iucmp", _primitive "Iucmp"),
  ("itoI", _primitive "itoI"),
  ("Itoi", _primitive "Itoi"),
  ("utoU", _primitive "utoU"),
  ("Utou", _primitive "Utou"),
  ("Wknew", _primitive "Wknew"),
  ("Wknewfin", _primitive "Wknewfin"),
  ("Wkderef", _primitive "Wkderef"),
  ("Wkfinal", _primitive "Wkfinal"),
  ("IO.getmaskingstate", _primitive "IO.getmaskingstate"),
  ("IO.setmaskingstate", _primitive "IO.setmaskingstate"),
  ("IO.pp", _primitive "IO.pp"),

  ("D_1", _primitive "D_1"),
  ("D_2", _primitive "D_2"),
  ("D_3", _primitive "D_3"),
  ("D_4", _primitive "D_4"),
  ("D_5", _primitive "D_5"),
  ("D_6", _primitive "D_6"),
  ("D_7", _primitive "D_7"),
  ("D_8", _primitive "D_8"),
  ("D_9", _primitive "D_9"),
  ("D_10", _primitive "D_10"),
  ("D_11", _primitive "D_11"),
  ("D_12", _primitive "D_12"),
  ("D_13", _primitive "D_13"),
  ("D_14", _primitive "D_14"),
  ("D_15", _primitive "D_15"),
  ("D_16", _primitive "D_16"),
  ("D_17", _primitive "D_17"),
  ("D_18", _primitive "D_18"),
  ("D_19", _primitive "D_19"),
  ("D_20", _primitive "D_20"),
  ("D_21", _primitive "D_21"),
  ("D_22", _primitive "D_22"),
  ("D_23", _primitive "D_23"),
  ("D_24", _primitive "D_24"),
  ("D_25", _primitive "D_25"),
  ("D_26", _primitive "D_26"),
  ("D_27", _primitive "D_27"),
  ("D_28", _primitive "D_28"),
  ("D_29", _primitive "D_29"),
  ("D_30", _primitive "D_30"),
  ("D_31", _primitive "D_31"),

  ("C_0_0", _primitive "C_0_0"),
  ("C_0_1", _primitive "C_0_1"),
  ("C_0_2", _primitive "C_0_2"),
  ("C_0_3", _primitive "C_0_3"),
  ("C_0_4", _primitive "C_0_4"),
  ("C_0_5", _primitive "C_0_5"),
  ("C_0_6", _primitive "C_0_6"),
  ("C_0_7", _primitive "C_0_7"),
  ("C_0_8", _primitive "C_0_8"),
  ("C_0_9", _primitive "C_0_9"),
  ("C_0_10", _primitive "C_0_10"),
  ("C_0_11", _primitive "C_0_11"),
  ("C_0_12", _primitive "C_0_12"),
  ("C_0_13", _primitive "C_0_13"),
  ("C_0_14", _primitive "C_0_14"),
  ("C_0_15", _primitive "C_0_15"),
  ("C_0_16", _primitive "C_0_16"),
  ("C_0_17", _primitive "C_0_17"),
  ("C_0_18", _primitive "C_0_18"),
  ("C_0_19", _primitive "C_0_19"),

  ("C_1_0", _primitive "C_1_0"),
  ("C_1_1", _primitive "C_1_1"),
  ("C_1_2", _primitive "C_1_2"),
  ("C_1_3", _primitive "C_1_3"),
  ("C_1_4", _primitive "C_1_4"),
  ("C_1_5", _primitive "C_1_5"),
  ("C_1_6", _primitive "C_1_6"),
  ("C_1_7", _primitive "C_1_7"),
  
  ("C_2_0", _primitive "C_2_0"),
  ("C_2_1", _primitive "C_2_1"),
  ("C_2_2", _primitive "C_2_2"),
  ("C_2_3", _primitive "C_2_3"),
  ("C_2_4", _primitive "C_2_4"),
  ("C_2_5", _primitive "C_2_5"),
  ("C_2_6", _primitive "C_2_6"),
  ("C_2_7", _primitive "C_2_7"),
  
  ("C_3_0", _primitive "C_3_0"),
  ("C_3_1", _primitive "C_3_1"),
  ("C_3_2", _primitive "C_3_2"),
  ("C_3_3", _primitive "C_3_3"),
  ("C_3_4", _primitive "C_3_4"),
  ("C_3_5", _primitive "C_3_5"),
  ("C_3_6", _primitive "C_3_6"),
  ("C_3_7", _primitive "C_3_7"),
  
  ("C_4_0", _primitive "C_4_0"),
  ("C_4_1", _primitive "C_4_1"),
  ("C_4_2", _primitive "C_4_2"),
  ("C_4_3", _primitive "C_4_3"),
  ("C_4_4", _primitive "C_4_4"),
  ("C_4_5", _primitive "C_4_5"),
  ("C_4_6", _primitive "C_4_6"),
  ("C_4_7", _primitive "C_4_7"),
  
  ("C_5_0", _primitive "C_5_0"),
  ("C_5_1", _primitive "C_5_1"),
  ("C_5_2", _primitive "C_5_2"),
  ("C_5_3", _primitive "C_5_3"),
  ("C_5_4", _primitive "C_5_4"),
  ("C_5_5", _primitive "C_5_5"),
  ("C_5_6", _primitive "C_5_6"),
  ("C_5_7", _primitive "C_5_7"),
  
  ("C_6_0", _primitive "C_6_0"),
  ("C_6_1", _primitive "C_6_1"),
  ("C_6_2", _primitive "C_6_2"),
  ("C_6_3", _primitive "C_6_3"),
  ("C_6_4", _primitive "C_6_4"),
  ("C_6_5", _primitive "C_6_5"),
  ("C_6_6", _primitive "C_6_6"),
  ("C_6_7", _primitive "C_6_7"),
  
  ("C_7_0", _primitive "C_7_0"),
  ("C_7_1", _primitive "C_7_1"),
  ("C_7_2", _primitive "C_7_2"),
  ("C_7_3", _primitive "C_7_3"),
  ("C_7_4", _primitive "C_7_4"),
  ("C_7_5", _primitive "C_7_5"),
  ("C_7_6", _primitive "C_7_6"),
  ("C_7_7", _primitive "C_7_7"),
  
  ("C_8_0", _primitive "C_8_0"),
  ("C_8_1", _primitive "C_8_1"),
  ("C_8_2", _primitive "C_8_2"),
  ("C_8_3", _primitive "C_8_3"),
  ("C_8_4", _primitive "C_8_4"),
  ("C_8_5", _primitive "C_8_5"),
  ("C_8_6", _primitive "C_8_6"),
  ("C_8_7", _primitive "C_8_7"),
  
  ("C_9_0", _primitive "C_9_0"),
  ("C_9_1", _primitive "C_9_1"),
  ("C_9_2", _primitive "C_9_2"),
  ("C_9_3", _primitive "C_9_3"),
  ("C_9_4", _primitive "C_9_4"),
  ("C_9_5", _primitive "C_9_5"),
  ("C_9_6", _primitive "C_9_6"),
  ("C_9_7", _primitive "C_9_7"),
  
  ("C_10_0", _primitive "C_10_0"),
  ("C_10_1", _primitive "C_10_1"),
  ("C_10_2", _primitive "C_10_2"),
  ("C_10_3", _primitive "C_10_3"),
  ("C_10_4", _primitive "C_10_4"),
  ("C_10_5", _primitive "C_10_5"),
  ("C_10_6", _primitive "C_10_6"),
  ("C_10_7", _primitive "C_10_7"),

  ("C_11_0", _primitive "C_11_0"),
  ("C_11_1", _primitive "C_11_1"),
  ("C_11_2", _primitive "C_11_2"),
  ("C_11_3", _primitive "C_11_3"),
  ("C_11_4", _primitive "C_11_4"),
  ("C_11_5", _primitive "C_11_5"),
  ("C_11_6", _primitive "C_11_6"),
  ("C_11_7", _primitive "C_11_7"),
  
  ("C_12_0", _primitive "C_12_0"),
  ("C_12_1", _primitive "C_12_1"),
  ("C_12_2", _primitive "C_12_2"),
  ("C_12_3", _primitive "C_12_3"),
  ("C_12_4", _primitive "C_12_4"),
  ("C_12_5", _primitive "C_12_5"),
  ("C_12_6", _primitive "C_12_6"),
  ("C_12_7", _primitive "C_12_7"),
  
  ("C_13_0", _primitive "C_13_0"),
  ("C_13_1", _primitive "C_13_1"),
  ("C_13_2", _primitive "C_13_2"),
  ("C_13_3", _primitive "C_13_3"),
  ("C_13_4", _primitive "C_13_4"),
  ("C_13_5", _primitive "C_13_5"),
  ("C_13_6", _primitive "C_13_6"),
  ("C_13_7", _primitive "C_13_7"),
  
  ("C_14_0", _primitive "C_14_0"),
  ("C_14_1", _primitive "C_14_1"),
  ("C_14_2", _primitive "C_14_2"),
  ("C_14_3", _primitive "C_14_3"),
  ("C_14_4", _primitive "C_14_4"),
  ("C_14_5", _primitive "C_14_5"),
  ("C_14_6", _primitive "C_14_6"),
  ("C_14_7", _primitive "C_14_7"),
  
  ("C_15_0", _primitive "C_15_0"),
  ("C_15_1", _primitive "C_15_1"),
  ("C_15_2", _primitive "C_15_2"),
  ("C_15_3", _primitive "C_15_3"),
  ("C_15_4", _primitive "C_15_4"),
  ("C_15_5", _primitive "C_15_5"),
  ("C_15_6", _primitive "C_15_6"),
  ("C_15_7", _primitive "C_15_7"),
  
  ("C_16_0", _primitive "C_16_0"),
  ("C_16_1", _primitive "C_16_1"),
  ("C_16_2", _primitive "C_16_2"),
  ("C_16_3", _primitive "C_16_3"),
  ("C_16_4", _primitive "C_16_4"),
  ("C_16_5", _primitive "C_16_5"),
  ("C_16_6", _primitive "C_16_6"),
  ("C_16_7", _primitive "C_16_7"),
  
  ("C_17_0", _primitive "C_17_0"),
  ("C_17_1", _primitive "C_17_1"),
  ("C_17_2", _primitive "C_17_2"),
  ("C_17_3", _primitive "C_17_3"),
  ("C_17_4", _primitive "C_17_4"),
  ("C_17_5", _primitive "C_17_5"),
  ("C_17_6", _primitive "C_17_6"),
  ("C_17_7", _primitive "C_17_7"),
  
  ("C_18_0", _primitive "C_18_0"),
  ("C_18_1", _primitive "C_18_1"),
  ("C_18_2", _primitive "C_18_2"),
  ("C_18_3", _primitive "C_18_3"),
  ("C_18_4", _primitive "C_18_4"),
  ("C_18_5", _primitive "C_18_5"),
  ("C_18_6", _primitive "C_18_6"),
  ("C_18_7", _primitive "C_18_7"),
  
  ("C_19_0", _primitive "C_19_0"),
  ("C_19_1", _primitive "C_19_1"),
  ("C_19_2", _primitive "C_19_2"),
  ("C_19_3", _primitive "C_19_3"),
  ("C_19_4", _primitive "C_19_4"),
  ("C_19_5", _primitive "C_19_5"),
  ("C_19_6", _primitive "C_19_6"),
  ("C_19_7", _primitive "C_19_7"),
  
  ("C_20_0", _primitive "C_20_0"),
  ("C_20_1", _primitive "C_20_1"),
  ("C_20_2", _primitive "C_20_2"),
  ("C_20_3", _primitive "C_20_3"),
  ("C_20_4", _primitive "C_20_4"),
  ("C_20_5", _primitive "C_20_5"),
  ("C_20_6", _primitive "C_20_6"),
  ("C_20_7", _primitive "C_20_7"),

  ("C_21_0", _primitive "C_21_0"),
  ("C_21_1", _primitive "C_21_1"),
  ("C_21_2", _primitive "C_21_2"),
  ("C_21_3", _primitive "C_21_3"),
  ("C_21_4", _primitive "C_21_4"),
  ("C_21_5", _primitive "C_21_5"),
  ("C_21_6", _primitive "C_21_6"),
  ("C_21_7", _primitive "C_21_7"),
  
  ("C_22_0", _primitive "C_22_0"),
  ("C_22_1", _primitive "C_22_1"),
  ("C_22_2", _primitive "C_22_2"),
  ("C_22_3", _primitive "C_22_3"),
  ("C_22_4", _primitive "C_22_4"),
  ("C_22_5", _primitive "C_22_5"),
  ("C_22_6", _primitive "C_22_6"),
  ("C_22_7", _primitive "C_22_7"),
  
  ("C_23_0", _primitive "C_23_0"),
  ("C_23_1", _primitive "C_23_1"),
  ("C_23_2", _primitive "C_23_2"),
  ("C_23_3", _primitive "C_23_3"),
  ("C_23_4", _primitive "C_23_4"),
  ("C_23_5", _primitive "C_23_5"),
  ("C_23_6", _primitive "C_23_6"),
  ("C_23_7", _primitive "C_23_7"),
  
  ("C_24_0", _primitive "C_24_0"),
  ("C_24_1", _primitive "C_24_1"),
  ("C_24_2", _primitive "C_24_2"),
  ("C_24_3", _primitive "C_24_3"),
  ("C_24_4", _primitive "C_24_4"),
  ("C_24_5", _primitive "C_24_5"),
  ("C_24_6", _primitive "C_24_6"),
  ("C_24_7", _primitive "C_24_7"),
  
  ("C_25_0", _primitive "C_25_0"),
  ("C_25_1", _primitive "C_25_1"),
  ("C_25_2", _primitive "C_25_2"),
  ("C_25_3", _primitive "C_25_3"),
  ("C_25_4", _primitive "C_25_4"),
  ("C_25_5", _primitive "C_25_5"),
  ("C_25_6", _primitive "C_25_6"),
  ("C_25_7", _primitive "C_25_7"),
  
  ("C_26_0", _primitive "C_26_0"),
  ("C_26_1", _primitive "C_26_1"),
  ("C_26_2", _primitive "C_26_2"),
  ("C_26_3", _primitive "C_26_3"),
  ("C_26_4", _primitive "C_26_4"),
  ("C_26_5", _primitive "C_26_5"),
  ("C_26_6", _primitive "C_26_6"),
  ("C_26_7", _primitive "C_26_7"),
  
  ("C_27_0", _primitive "C_27_0"),
  ("C_27_1", _primitive "C_27_1"),
  ("C_27_2", _primitive "C_27_2"),
  ("C_27_3", _primitive "C_27_3"),
  ("C_27_4", _primitive "C_27_4"),
  ("C_27_5", _primitive "C_27_5"),
  ("C_27_6", _primitive "C_27_6"),
  ("C_27_7", _primitive "C_27_7"),
  
  ("C_28_0", _primitive "C_28_0"),
  ("C_28_1", _primitive "C_28_1"),
  ("C_28_2", _primitive "C_28_2"),
  ("C_28_3", _primitive "C_28_3"),
  ("C_28_4", _primitive "C_28_4"),
  ("C_28_5", _primitive "C_28_5"),
  ("C_28_6", _primitive "C_28_6"),
  ("C_28_7", _primitive "C_28_7"),
  
  ("C_29_0", _primitive "C_29_0"),
  ("C_29_1", _primitive "C_29_1"),
  ("C_29_2", _primitive "C_29_2"),
  ("C_29_3", _primitive "C_29_3"),
  ("C_29_4", _primitive "C_29_4"),
  ("C_29_5", _primitive "C_29_5"),
  ("C_29_6", _primitive "C_29_6"),
  ("C_29_7", _primitive "C_29_7"),
  
  ("C_30_0", _primitive "C_30_0"),
  ("C_30_1", _primitive "C_30_1")
  ]
