-- Copyright 2023,2024 Lennart Augustsson
-- See LICENSE file for full license.
module AllOfLib(main) where
-- Only used to save the compilation cache.
import Compat
import Control.Applicative
import Control.DeepSeq
import Control.Error
import Control.Exception
import Control.Monad
import Control.Monad.Fail
import Control.Monad.ST
import Control.Monad.State.Strict
import Data.Bits
import Data.Bool
import Data.Bool_Type
import Data.Bounded
import Data.Char
import Data.Char_Type
import Data.Complex
import Data.Constraint
import Data.Double
import Data.Dynamic
import Data.Either
import Data.Enum
import Data.Eq
import Data.Floating
import Data.Foldable
import Data.Fractional
import Data.Function
import Data.Functor
import Data.Functor.Const
import Data.Functor.Identity
import Data.IOArray
import Data.IORef
import Data.Int
import Data.IntMap
import Data.IntSet
import Data.Integer
import Data.Integer_Type
import Data.Integral
import Data.List
import Data.List_Type
import Data.Map
import Data.Maybe
import Data.Maybe_Type
import Data.Monoid
import Data.Num
import Data.Ord
import Data.Ordering_Type
import Data.Proxy
import Data.Ratio
import Data.Ratio_Type
import Data.Real
import Data.RealFloat
import Data.RealFrac
import Data.Records
import Data.Semigroup
import Data.STRef
import Data.Traversable
import Data.Tuple
import Data.Typeable
import Data.TypeLits
import Data.Void
import Data.Word
import Data.Word8
import Data.ZipList
import Debug.Trace
import Foreign.C.String
import Foreign.Marshal.Alloc
import Foreign.Marshal.Array
import Foreign.Marshal.Utils
import Foreign.Ptr
import Foreign.Storable
import GHC.Stack
import GHC.Types
import Numeric
import Prelude
import Primitives
import System.Console.SimpleReadline
import System.Directory
import System.Environment
import System.Exit
import System.IO
import System.IO.MD5
import System.IO.PrintOrRun
import System.Process
import Text.PrettyPrint.HughesPJ
import Text.Read
import Text.Show
import Text.String
import Unsafe.Coerce

main :: IO ()
main = return ()
